### ISSUE TITLE
i think i messed up

### ISSUE THREAD

**Issue by theMkeyholder** [Yoreni/Ultimate-Incremental#7]
i tried making the click button a canvas but that messed the code up...

**Comment by Yoreni** [comment]
ok i fixed it was not working because when put the text on the onclick event that the javascript function it calls so you need to but the open and close brackets on the end other wise it wont work and the button did not get is backgroud because it was not in the CSS so i changed it if you want to give a canvas a background now put class="buttonBackground" in the html tag thingy
